cmd.exe /c "forever --version || npm i forever -g"
cmd.exe /c "npm install"
cmd.exe /c "cd ./react/"
cmd.exe /c "npm install"
cmd.exe /c "cd .."
cmd.exe /c "forever stopall"
cmd.exe /c "forever start ./server.js"
cmd.exe /c "start http://localhost:3001/"